<a href="https://colab.research.google.com/github/Iftikhar-Shams-Niloy/Python-Numpy-Pandas/blob/main/Numpy_Library_Cookbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **<<< Numpy >>>**

In [2]:
# First we will import the numpy libary as np
import numpy as np

## Making An Array


In [3]:
# First we define a list
myList = [10,20,30,40,50]
print(myList)
type(myList)

[10, 20, 30, 40, 50]


list

In [4]:
# Then we can convert the list into an array using np.array() method
myArray = np.array(myList)
print(myArray)
print(type(myArray))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [5]:
# We can also convert a nested list into a 3D Matrix using np.array() method
nested_list = [[11,22,33],[44,55,66],[77,88,99]]
my_matrix = np.array(nested_list)
print(np.array(my_matrix))
print(type(my_matrix))

[[11 22 33]
 [44 55 66]
 [77 88 99]]
<class 'numpy.ndarray'>


### np.arange()

In [6]:
# We can also generate n values of same differentce array using np.arange()
myArange1 = np.arange(0,10) # np.arange(start, end)
myArange2 = np. arange(0,101, 10) # np.arange(start, end, step)
print("myArrange1 : ", myArange1)
print("myArrange2 : ", myArange2)
print(type(myArange1))

myArrange1 :  [0 1 2 3 4 5 6 7 8 9]
myArrange2 :  [  0  10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


### np.zeros() , np.ones() , np.eye()

In [7]:
zeroArray1 = np.zeros(10)
zeroArray2 = np.zeros((3,5)) # np.zeros((row, column))
oneArray = np.ones((3,5))
eyeArray = np.eye(5) # Creates identical matrix of "n" column and rows
print("zeroArray1 : \n",zeroArray1)
print("zeroArray2 : \n",zeroArray2)
print("oneArray = \n",oneArray)
print("eyeArray = \n", eyeArray)

zeroArray1 : 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
zeroArray2 : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
oneArray = 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
eyeArray = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### np.linspace()

In [17]:
myLinespace = np.linspace(0,10,11) # np.linespace(start, end, num_of_values)
print(myLinespace)
print(type(myLinespace)) # type of myLinespace
print(myLinespace.dtype) # type of the values inside myLinespace

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
float64


### np.random

In [11]:
np.random.seed(42) # np.random.seed() will make the program to generate the same set of random numbers everytime I run the code snippet.

# np.random.rand() generates an array of random "uniform distribution"(from 0 to 1) of data
myRandom1 = np.random.rand(10) # creates an 1D Array of 10 values
myRandom2 = np.random.rand(5,2) #np.random.rand(number_of_rows, number_of_colums)

# np.random.randn() generates an array of random "standard normal distribution" datas
myRandom3 = np.random.randn(5,2)

# np.random.randint() genrates an array of random integer numbers. (Can be 1D or Multi-dimentional)
myRandom4 = np.random.randint(1,11) # Generates 'SINGELE' integer number between 1 to 10
myRandom5 = np.random.randint(1,11,5) # Generates 5 random integer number between 1 to 10
myRandom6 = np.random.randint(1,11,(3,5)) # Generates 2-rows and 3-columns of random integer number between 1 to 10

print(myRandom1) # 1D array
print(myRandom2)
print("===============================")
print(myRandom3)
print("===============================")
print(myRandom4)
print(myRandom5)
print(myRandom6)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
[[0.02058449 0.96990985]
 [0.83244264 0.21233911]
 [0.18182497 0.18340451]
 [0.30424224 0.52475643]
 [0.43194502 0.29122914]]
[[-1.01283112  0.31424733]
 [-0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763 ]
 [ 0.0675282  -1.42474819]
 [-0.54438272  0.11092259]]
3
[7 5 9 7 2]
[[ 4  9  2 10  9]
 [10  5  2  4  7]
 [ 8  3  1  4  2]]


### myArr.reshape()

In [15]:
myArr = np.arange(1,51) # This creates an 1D array of numbers from 1 to 50
print("This is myArr:\n",myArr)

myReshape = myArr.reshape(5,10) # This converts the Array into 5 rows and 10 columns
print("This is myReshape:\n",myReshape)

'''
If the .reshape() parameters multiplication result for row and column does not match
with the total number of values in myArr, then python will trow an error.
'''

This is myArr:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
This is myReshape:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


'\nIf the .reshape() parameters multiplication result for row and column does not match \nwith the total number of values in myArr, then python will trow an error.\n'

.max()
.min()
.argmax()
.argmin()
.shape()

In [24]:
myArr = np.array([1,2,30,4,5])
print("Gives the MAXIMUM value inside the array:",myArr.max())
print("Gives the MINIMUM value inside the array:",myArr.min())
print("Gives the INDEX of MAXIMUM value inside the array:",myArr.argmax())
print("Gives the INDEX of MINIMUM value inside the array:",myArr.argmin())
print("Gives the array shape:", myArr.shape)
# np.shape gives result like this, (row, column) when multidimentional
# np.shape gives result like this, (no_of_values,) when one dimentional

Gives the MAXIMUM value inside the array: 30
Gives the MINIMUM value inside the array: 1
Gives the INDEX of MAXIMUM value inside the array: 2
Gives the INDEX of MINIMUM value inside the array: 0
Gives the array shape: (5,)
