# **<<< Numpy >>>**

In [1]:
# First we will import the numpy libary as np
import numpy as np

## Making An Array


In [5]:
# First we define a list
myList = [10,20,30,40,50]
print(myList)
type(myList)

[10, 20, 30, 40, 50]


list

In [7]:
# Then we can convert the list into an array using np.array() method
myArray = np.array(myList)
print(myArray)
print(type(myArray))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [9]:
# We can also convert a nested list into a 3D Matrix using np.array() method
nested_list = [[11,22,33],[44,55,66],[77,88,99]]
my_matrix = np.array(nested_list)
print(np.array(my_matrix))
print(type(my_matrix))

[[11 22 33]
 [44 55 66]
 [77 88 99]]
<class 'numpy.ndarray'>


### np.arange()

In [12]:
# We can also generate n values of same differentce array using np.arange()
myArange1 = np.arange(0,10) # np.arange(start, end)
myArange2 = np. arange(0,101, 10) # np.arange(start, end, step)
print("myArrange1 : ", myArange1)
print("myArrange2 : ", myArange2)
print(type(myArange1))

myArrange1 :  [0 1 2 3 4 5 6 7 8 9]
myArrange2 :  [  0  10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


### np.zeros() , np.ones() , np.eye()

In [22]:
zeroArray1 = np.zeros(10)
zeroArray2 = np.zeros((3,5)) # np.zeros((row, column))
oneArray = np.ones((3,5))
eyeArray = np.eye(5) # Creates identical matrix of "n" column and rows
print("zeroArray1 : \n",zeroArray1)
print("zeroArray2 : \n",zeroArray2)
print("oneArray = \n",oneArray)
print("eyeArray = \n", eyeArray)

zeroArray1 : 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
zeroArray2 : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
oneArray = 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
eyeArray = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### np.linspace()

In [20]:
myLinespace = np.linspace(0,10,11) # np.linespace(start, end, num_of_values)
print(myLinespace)
print(type(myLinespace)) # type of myLinespace
print(type(myLinespace[0])) # type of each element of myLinespace

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


### np.random

In [32]:
# np.random.rand() generates an array of random "uniform distribution"(from 0 to 1) of data
myRandom1 = np.random.rand(10) # creates an 1D Array of 10 values
myRandom2 = np.random.rand(5,2) #np.random.rand(number_of_rows, number_of_colums)

# np.random.randn() generates an array of random "standard normal distribution" datas
myRandom3 = np.random.randn(5,2)

# np.random.randint() genrates an array of random integer numbers. (Can be 1D or Multi-dimentional)
myRandom4 = np.random.randint(1,11) # Generates 'SINGELE' integer number between 1 to 10
myRandom5 = np.random.randint(1,11,5) # Generates 5 random integer number between 1 to 10
myRandom6 = np.random.randint(1,11,(3,5)) # Generates 2-rows and 3-columns of random integer number between 1 to 10

print(myRandom1) # 1D array
print(myRandom2)
print("===============================")
print(myRandom3)
print("===============================")
print(myRandom4)
print(myRandom5)
print(myRandom6)

[0.76551775 0.63012444 0.79435563 0.75682307 0.34339847 0.32464837
 0.12152236 0.72803258 0.77728084 0.4789075 ]
[[0.22423997 0.35232987]
 [0.00187007 0.16824104]
 [0.09934266 0.44466068]
 [0.51339537 0.59394785]
 [0.90254519 0.91952913]]
[[ 0.65295098 -0.52508447]
 [-1.48872387  0.71762175]
 [-0.74769257 -0.70053284]
 [-1.60190198  0.07673065]
 [ 0.38816767 -0.77670233]]
10
[2 8 2 7 5]
[[ 9  2  3  1  4]
 [ 3  7  1  3 10]
 [ 7  9  2 10  8]]
